name: Build on Ubuntu
on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10.1.0"]
        ghc: ["9.2.7"]
    steps:

      - name: Install imagemagick and ghostscript
        run: sudo apt-get install -y imagemagick ghostscript

      - name: Update the imagemagick policy
        run: sudo sed -i_bak 's/rights="none" pattern="PDF"/rights="read | write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml

      #- name: Test fucking config
      #  run: cat /etc/ImageMagick-6/policy.xml

      # Install haskell and friends 
      - name: Install dependencies
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '${{ matrix.ghc }}'
          cabal-version: '${{ matrix.cabal }}'

      # Cache cabal and the blog
      - name: Cache ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            ~/dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}

      # Get the sources
      - name: Checkout site
        uses: actions/checkout@v2

      # Do the build
      - name: Build site
        run: |
          cabal build
          cabal exec artem-blog build

      # Copy the actual html
      - name: Deploy HTML
        uses: JamesIves/github-pages-deploy-action@4.1.3

        with:
          branch: master
          folder: _site
          git-config-name: Github Actions
