name: Build on Ubuntu
on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.10.1.0"]
        ghc: ["9.2.7"]
    steps:

      - name: Install imagemagick
        run: sudo apt-get install -y imagemagick

########################################################################
## INSTALLATION STEP
########################################################################

      - name: Install dependencies
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '${{ matrix.ghc }}'
          cabal-version: '${{ matrix.cabal }}'

      - name: Cache ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            ~/dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cabal }}

########################################################################
## BUILD STEP
########################################################################

      # By default github actions do not pull the repo
      - name: Checkout site
        uses: actions/checkout@v2

      - name: Build site
        run: |
          cabal build
          cabal exec artem-blog build

########################################################################
## DEPLOY STEP
########################################################################

      - name: Deploy HTML
        uses: JamesIves/github-pages-deploy-action@4.1.3

        with:
          branch: master
          folder: _site
          git-config-name: Github Actions
